version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0.4
  shellcheck: circleci/shellcheck@3.1
  bats: circleci/bats@1.1.0
  mattermost-plugin-notify: nathanaelhoun/mattermost-plugin-notify@1.2.0

filters: &filters
  tags:
    only: /.*/

executors:
  default:
    docker:
      - image: cimg/base:stable
  macos-executor:
    macos:
      xcode: 12.2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  unit-test-executor:
    description: Executor for the unit tests. Can be default or macos-executor
    type: string
    default: default
  build_output:
    description: The output directory for the build
    type: enum
    default: linux-64
    enum: ["linux-64", "osx-64"]

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
          exclude: "RC002,RC009,RC010"
      - shellcheck/check:
          filters: *filters
      - bats/run:
          name: unit-tests
          path: ./src/tests
          exec_environment: << pipeline.parameters.unit-test-executor >>
      # If you accept building open source forks, protect your secrects behind a restricted context.
      # A job containing restricted context (which holds your orb publishing credentials) may only be accessed by a user with proper permissions.
      # An open source user may begin a pipeline with a PR, and once the pipeline is approved by an authorized user at this point, the pipeline will continue with the proper context permissions.
      - mattermost-plugin-notify/approval-notification:
          message: Hello @all! A workflow on https://app.circleci.com/pipelines/github/psyplot/psyplot-ci-orb is awaiting your approval.
          context: mattermost
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - unit-tests
            - shellcheck/check
      - hold-for-dev-publish:
          type: approval
          requires:
            - mattermost-plugin-notify/approval-notification
      # Publish development version(s) of the orb.
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: <orb-name>
          requires: [hold-for-dev-publish]
          filters: *filters
