description: "Configure miniconda"
parameters:
  condadir:
    description: "Install location for anaconda"
    type: string
    default: "~/miniconda3"
  recipe_dir:
    description: Path to the recipe to build relative to the project directory
    type: string
    default: ci/conda-recipe
  python_version:
    description: Python version
    type: string
    default: "3.8"
steps:
  - run:
      environment:
        CONDADIR: <<parameters.condadir>>
        RECIPEDIR: <<parameters.recipe_dir>>
        PYTHON_VERSION: <<parameters.python_version>>
      name: Build recipe
      command: <<include(scripts/conda_build.sh)>>
