description: "Configure miniconda"
parameters:
  condadir:
    description: Install location for anaconda
    type: string
    default: "~/miniconda3"
  main_channel:
    description: Main channel to use with channels and for the branches
    type: string
    default: psyplot
  default_branch:
    description: Default branch channel for conda
    type: string
    default: master
  channels:
    description: Further default channels for conda
    type: string
    default: conda-forge
  packages:
    description: Extra packages to install into the base environment
    type: string
    default: conda-build anaconda-client conda-verify
steps:
  - run:
      environment:
        CONDADIR: <<parameters.condadir>>
        MAINCHANNEL: <<parameters.main_channel>>
        DEFAULTBRANCH: <<parameters.default_branch>>
        CHANNELS: <<parameters.channels>>
        PACKAGES: <<parameters.packages>>
      name: Configure conda
      command: <<include(scripts/configure-conda.sh)>>
