description: "Configure the recipe with extra options"
parameters:
  recipe_dir:
    description: Path to the recipe to build relative to the project directory
    type: string
    default: ci/conda-recipe
  recipe_append:
    description: The full content for recipe_append.yml
    type: string
steps:
  - run:
      environment:
        RECIPEDIR: <<parameters.recipe_dir>>
        RECIPEAPPEND: <<parameters.pythonrecipe_append_version>>
      name: Configure the recipe
      command: <<include(scripts/configure-recipe.sh)>>
