description: "Configure miniconda"
parameters:
  condadir:
    description: Install location for anaconda
    type: string
    default: "~/miniconda3"
  main_channel:
    description: Main channel to use with channels and for the branches
    type: string
    default: psyplot
  default_branch:
    description: Default branch channel for conda
    type: string
    default: develop
  channels:
    description: Further default channels for conda
    type: string
    default: conda-forge
  branch_label:
    description: Use the branch name as a label for the anaconda channel
    type: boolean
    default: true
  packages:
    description: Extra packages to install into the base environment
    type: string
    # we use conda-build=3.25.* as 3.26.0 fails for unknown reasons
    default: "conda-build=3.25.* anaconda-client conda-verify"
  orb_version:
    description: >
      Version for the python deploy package to use. See
      https://anaconda.org/psyplot/psyplot-ci-orb
    type: string
    default: "1.5.33"
steps:
  - run:
      environment:
        CONDADIR: <<parameters.condadir>>
        MAINCHANNEL: <<parameters.main_channel>>
        DEFAULTBRANCH: <<parameters.default_branch>>
        CHANNELS: <<parameters.channels>>
        PACKAGES: <<parameters.packages>>
        USE_BRANCH: <<# parameters.branch_label >>1<</ parameters.branch_label >>
        ORB_VERSION: << parameters.orb_version >>
      name: Configure conda
      command: <<include(scripts/configure-conda.sh)>>
  - run:
      environment:
        CONDADIR: <<parameters.condadir>>
      name: conda info
      command: <<include(scripts/conda-info.sh)>>
